name: Android test
on: [push]
jobs:
  Android-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.5"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: ncipollo/release-action@v1
        name: Create Github Release 
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.GITHUB_TOKEN }}
